#!/bin/bash
. configuration
. common
. .stationrc

qdebug=1
if [ "x$1" = "x" ];then qdebug=0;fi

j=0
while [ 1 ]
do
    # CHECK IF STOP SIGNAL HAVE BEEN SENT
    if [ -e stop ];then 
	echo "Stopping."
	exit 0
    fi

    # UPDATE BRANCH
    echo "Updating repository..."
    make pull

    # RUN PROCESS PER EACH PROCESSOR
    for i in $(seq 1 $station_nproc)
    do
	if [ $qdebug -eq 0 ];then
	    python tquakes-pipeline.py >> log/tquakes-proc$i.log &
	    sleep 1
	else
	    echo "Process $i/$station_nproc..."
	    python tquakes-pipeline.py
	fi
    done
    
    # WAIT UNTIL PROCESSES END
    wait
    ((j++))

    # BREAK AFTER 
    if [ $j -gt $DAEMON_LIMIT ];then exit 0;fi
done
